server:
  port: 8000
  # 设置Session有效时间，即超过多长时间用户无操作session就失效，单位是秒，系统默认是30分钟
  servlet:
    session:
      timeout: 30m
      # max-age=-1,代表浏览器关闭 JSESSIONID就会失效，网上的方法
      cookie:
        max-age: -1


mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    com.tsien.poros.dao: debug
  file:
    path: ./logs

spring:
  profiles:
    active: prod
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

---
spring:
  datasource:
    druid:
      name: druidDatasource
      url: jdbc:mysql://localhost:3306/poros?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: 16601130186
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      enabled: true
      max-file-size: 4MB
      max-request-size: 10MB
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8

  profiles: prod
